# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-29 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_goods_picture_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='u_phone',
            field=models.IntegerField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='u_password',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
