# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-29 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20190629_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_phone',
            field=models.IntegerField(default=''),
        ),
    ]
