# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-11 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_indent_order_shipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='time',
        ),
        migrations.AddField(
            model_name='order',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='oselect',
            field=models.BooleanField(default='1'),
        ),
        migrations.AlterField(
            model_name='order',
            name='gid',
            field=models.ForeignKey(db_column='good', on_delete=django.db.models.deletion.CASCADE, related_name='order_good', to='App.Good'),
        ),
        migrations.AlterField(
            model_name='order',
            name='uid',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to='App.User'),
        ),
    ]
