# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-29 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20190629_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_phone',
            field=models.IntegerField(unique=True),
        ),
    ]
